### ISSUE TITLE
The application webpage can't be displayed correctly.

### ISSUE THREAD

**Issue by ibmalan** [watson-developer-cloud/social-customer-care#14]
1. I downloaded the latest sample code and deployed it again, the issue#13 still exist.  after deployment is completed successfully, check it from bluemix dashboard, the web application can't display correctly.

2.  During deployment, if use env.js instead of .env.js directly, then the application will be crashed all the time.  please check the attachment log.
[crash information.txt](https://github.com/watson-developer-cloud/social-customer-care/files/561186/crash.information.txt)

**Comment by germanattanasio** [comment]
I deployed the app without issues @ibmalan. Can you check again?
