### ISSUE TITLE
Feedback from the developer productivity team - https://ibm-bluemix.github.io

### ISSUE THREAD

**Issue by Twanawebtech** [watson-developer-cloud/social-customer-care#17]
@germanattanasio we have reviewed this sample as we thought it would be a good sample to be featured part of the https://ibm-bluemix.github.io/ page where developers can find Bluemix featured samples. 

I want share some feedback by our team who reviewed this demo:
**Person 1)** I don't "get" the live demo ... just not clear what it's doing. 
is there a link to any blog referencing this sample ?

**Person 2)** I like the concept ( from thinking about it and reading ). The site is visually well done - but the context is missing - you have to work out what it is doing. I'd give it a stronger thumbs up if it had more context.

**Person 3)** I like this example very much, it lacks the proper intro. I would love to see the video blog demonstrating the deployment. With the updated informative info I would love to give it thumbs up (or video blog).

**Person 4)** More work needed in understand how to work with the live demo.

----

**I would love to feature this sample if the points above get looked at.**

**Comment by germanattanasio** [comment]
@priumoraes can you talk to Laura, I think this is valuable feedback. We want Bluemix to add this sample to  https://ibm-bluemix.github.io/.

Maybe we can write a blog or create a video to describe what this app does.

**Comment by Twanawebtech** [comment]
@priumoraes any updates on above?

**Comment by ljbennett62** [comment]
Hi - i have a new front-end developer who is starting in a couple of weeks (Mar 6) - I will have him work on this.

**Comment by Twanawebtech** [comment]
Awesome, keep me posted.

**Comment by Twanawebtech** [comment]
@ljbennett62 @germanattanasio I am closing the issue for featuring this sample. 
I see no updates made to above feedback. 

This sample won't be featured until above feedback looked at.

Feel free to submit your sample again when updates are made to this, you can submit your sample to be featured on the IBM site by clicking on the "Submit Your Sample" button on this https://ibm-bluemix.github.io/#!/ page.
